networks:
  default:

services:
  bedrock:
    build:
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./docker-volumes:/app/results
    networks:
      - default
    command: ["python", "testharness.py"]
